logging:
  level:
    root: INFO

spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:9999/jikanganai
  #    driver: org.postgresql.Driver
  #    username: postgres
  #    password: password
  #    name: jikanganai
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true