logging:
  level:
    root: INFO
    org.springframework: INFO
    graphql: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE

kafka:
  bootstrapAddress: "http://192.168.1.111:9092"
  topic: "datastream"

graphql:
  url: "graphql"

neo4j:
  properties:
    url: "neo4j://localhost:7687"
    username: neo4j
    password: test

spring:
  data:
    neo4j:
      username: neo4j
      password: test
